# Laravel Railway Configuration

php_version: 8.3
build:
  - composer install --no-dev --optimize-autoloader
  - php artisan config:cache
  - php artisan route:cache
  - php artisan view:cache
  - npm ci
  - npm run build