[phases.setup]
nixPkgs = ["php8.2", "nodejs-18_x", "npm-8_x"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "chmod -R 777 storage bootstrap/cache public",
  "mkdir -p storage/framework/sessions",
  "chmod -R 777 storage/framework/sessions",
  "php artisan key:generate --force",
  "php artisan storage:link || true",
  "php artisan config:clear",
  "php artisan cache:clear",
  "php artisan view:clear",
  "php artisan migrate:fresh --force --seed",
  "php artisan optimize:clear",
  "php artisan optimize",
  "npm ci",
  "npm run build"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT} --no-reload"